### ISSUE TITLE
Upload the reference file?

### ISSUE THREAD

**Issue by pleasebelucky** [leeju-umich/Cho_Xi_Seqscope#3]
Hi!

Thanks for the great work! It would be great if you can upload the Reference genome and STAR index in mm10 under GenomeDir folder or provide more information on choosing the reference.

Thank you!

**Comment by hyunminkang** [comment]
Hi, the genome index is too big to put it in the GitHub, and it is redundant to publicly available resources. Nevertheless, below is an instruction how to create one. You do not have to follow these steps and can create one from public mm10 FASTA and GTF. I hope this helps.

```
python -m pip install gdown
gdown https://drive.google.com/uc?id=1e0u57Yu_fVKFvs-UA7WYfj-vgm8Nd2y4
unzip STtools_example_data.zip 
mkdir -p STtools_example_data/geneIndex/STARIndex
STAR --runThreadN 6 --runMode genomeGenerate --genomeDir \
     STtools_example_data/geneIndex/STARIndex \
     --genomeFastaFiles STtools_example_data/geneIndex/mm10.fasta \
     --sjdbGTFfile STtools_example_data/geneIndex/mm10.gtf --sjdbOverhang 99
```
